# Generated by Django 2.1.3 on 2019-01-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190115_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='', upload_to='profile_pics'),
        ),
    ]
