# Generated by Django 2.1.3 on 2019-01-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190118_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(blank=True, default='new.jpg', null=True, upload_to='media'),
        ),
    ]
